# Generated by Django 5.0 on 2024-03-01 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_tophotels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tophotels',
            old_name='Style',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='tophotels',
            old_name='Attractions',
            new_name='highlights',
        ),
        migrations.RenameField(
            model_name='tophotels',
            old_name='place',
            new_name='hotelname',
        ),
        migrations.RenameField(
            model_name='tophotels',
            old_name='title',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='tophotels',
            name='photo',
            field=models.ImageField(upload_to='static/img/hotels'),
        ),
    ]
